name: yakihonne
description: YakiHonne social platform.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.9.5+171

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  aescryptojs: ^1.0.0
  amberflutter:
    git:
      url: https://github.com/YakiHonne/amberflutter.git
      ref: master
  animate_do: ^3.0.2
  app_links: ^6.3.2
  awesome_notifications: ^0.10.0
  bip340: ^0.3.0
  bolt11_decoder: ^1.0.2
  bot_toast: ^4.1.3
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.2.3
  calendar_date_picker2: ^1.1.7
  chat_gpt_sdk: ^3.1.4
  chewie: ^1.10.0
  connectivity_plus: ^6.0.5
  convert: ^3.1.1
  cookie_jar: ^4.0.8
  crypto: ^3.0.6
  custom_sliding_segmented_control: ^1.8.3
  deepl_dart: ^1.5.0
  device_info_plus: ^10.1.2
  dio: ^5.2.1+1
  dio_cookie_manager: ^3.1.0+1
  dropdown_button2: ^2.3.9
  emoji_picker_flutter: ^4.3.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  extended_image: ^8.3.1
  fc_native_video_thumbnail: ^0.12.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_file_saver: ^0.9.0
  flutter_highlight: ^0.7.0
  flutter_hooks: ^0.21.2
  flutter_inappwebview: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_link_previewer: ^3.2.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_math_fork:
    git:
      url: https://github.com/YakiHonne/flutter_math.git
      ref: main
  flutter_native_splash: ^2.4.1
  flutter_reorderable_grid_view: ^5.2.0
  flutter_scroll_shadow: ^1.2.3
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  form_field_validator: ^1.1.0
  giphy_api_client:
    git:
      url: https://github.com/YakiHonne/giphy_client.git
      ref: master
  glassmorphism: ^3.0.0
  html: ^0.15.4
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.2
  interactiveviewer_gallery_plus: ^0.1.0
  intl: ^0.20.2
  just_audio: ^0.9.39
  logger: ^2.4.0
  lottie: ^3.1.2
  markdown: ^7.3.0
  markdown_widget: ^2.3.2+6
  mention_tag_text_field: ^0.0.8
  modal_bottom_sheet: ^3.0.0
  nested_scroll_view_plus: ^2.0.0
  # nostr_core_enhanced:
  #   path: ../nostr_core_enhanced/
  nostr_core_enhanced:
    git:
      url: https://github.com/YakiHonne/nostr_core_enhanced.git
      ref: main
  numeral: ^3.0.0
  open_filex: ^4.7.0
  override_text_scale_factor: ^1.0.2
  pasteboard: ^0.4.0
  path: ^1.8.3
  path_drawing: ^1.0.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pretty_qr_code: ^3.4.0
  pull_down_button: ^0.10.2
  pull_to_refresh: ^2.0.0
  qr_code_scanner:
    git:
      url: https://github.com/YakiHonne/qr_code_scanner.git
      ref: master
  qr_flutter: ^4.1.0
  responsive_framework: ^1.1.0
  screenshot: ^3.0.0
  sentry_dart_plugin: ^3.1.1
  sentry_flutter: ^9.4.1
  share_handler: ^0.0.25
  share_plus: ^10.0.2
  shared_preferences: ^2.5.3
  sizer: ^2.0.14
  skeletonizer: ^2.1.0+1
  slang: ^4.8.1
  slang_flutter: ^4.4.0
  string_validator: ^1.0.2
  unifiedpush: ^5.0.2
  unifiedpush_android: ^2.0.0
  url_launcher: ^6.1.14
  uuid: ^4.3.3
  video_player: ^2.9.2
  video_url_validator: ^1.0.3
  visibility_detector: ^0.4.0+2
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.3

flutter_launcher_icons:
  android: true
  # ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/features/
    - assets/icons/logos/
    - assets/icons/toasts/
    - assets/images/
    - assets/lottie/
    - .env
    - shorebird.yaml

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Black.ttf
          weight: 900
        - asset: assets/fonts/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
